### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by ihydez** [Seji64/LAPS-WebUI#13]
Hello we want to implemented this solution but we have a error message,our config looks good

You can see this error here:

![image](https://github.com/Seji64/LAPS-WebUI/assets/116790795/895f47a6-1b25-4592-a880-35f73305a87d)

Can you help me please ? ;)

**Comment by ihydez** [comment]
My user is a member of the group to display passwords ;)

**Comment by ihydez** [comment]
we have laps V2

**Comment by Seji64** [comment]
I will try to to help. How does your `appsettings.json` look?

**Comment by ihydez** [comment]
![image](https://github.com/Seji64/LAPS-WebUI/assets/116790795/ef0c9646-b032-41a6-848d-8e94a3563f73)
This is my appsettings.json ;)

**Comment by Seji64** [comment]
- The 'a' at `ForceVersion` should be Capital. You can also omit the whole Setting cause you using the default.

- Are you sure enryption is disabled? On a default (laps) Installation encryption is enabled.
