### ISSUE TITLE
Default to V2 when the computer has a LAPSv2 password

### ISSUE THREAD

**Issue by magicvodi** [Seji64/LAPS-WebUI#15]
When I open a computer with a LAPSv2 Password the view defaults to the empty V1 and I have to click V2 to see the password. It would be nice if it shows the V2 password without an extra click.

**Comment by Seji64** [comment]
Set `ForceVersion` to `v2` if you don't want to see v1

**Comment by IBS-IT** [comment]
I set `ForceVersion` to `v2` and I always get this when I look up a password:

<img width="605" alt="image" src="https://github.com/Seji64/LAPS-WebUI/assets/110455996/c607ac1b-bf8e-494e-8cdb-47e8c582af7a">

I used the env variable `LAPS__ForceVersion`.
